/*
 * Payment Initiation API
 * Swagger for Payment Initiation API Specification
 *
 * OpenAPI spec version: v3.1.2-RC1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.org.openbanking.datamodel.payment;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import uk.org.openbanking.datamodel.Links;
import uk.org.openbanking.datamodel.Meta;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * OBWriteFileResponse2
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-13T16:03:12.161+01:00")
public class OBWriteFileResponse2 {
  @JsonProperty("Data")
  private OBWriteFileResponse2Data data = null;

  @JsonProperty("Links")
  private Links links = null;

  @JsonProperty("Meta")
  private Meta meta = null;

    public OBWriteFileResponse2 data(OBWriteFileResponse2Data data) {
    this.data = data;
    return this;
  }

    /**
   * Get data
   * @return data
  **/
  @NotNull
  @Valid
  @ApiModelProperty(required = true, value = "")
  public OBWriteFileResponse2Data getData() {
    return data;
  }

    public void setData(OBWriteFileResponse2Data data) {
    this.data = data;
  }

  public OBWriteFileResponse2 links(Links links) {
    this.links = links;
    return this;
  }

    /**
   * Get links
   * @return links
  **/
  @Valid
  @ApiModelProperty(value = "")
  public Links getLinks() {
    return links;
  }

  public void setLinks(Links links) {
    this.links = links;
  }

  public OBWriteFileResponse2 meta(Meta meta) {
    this.meta = meta;
    return this;
  }

    /**
   * Get meta
   * @return meta
  **/
  @Valid
  @ApiModelProperty(value = "")
  public Meta getMeta() {
    return meta;
  }

  public void setMeta(Meta meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OBWriteFileResponse2 obWriteFileResponse2 = (OBWriteFileResponse2) o;
    return Objects.equals(this.data, obWriteFileResponse2.data) &&
        Objects.equals(this.links, obWriteFileResponse2.links) &&
        Objects.equals(this.meta, obWriteFileResponse2.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, links, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OBWriteFileResponse2 {\n");

      sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

