/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2-RC1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.org.openbanking.datamodel.account;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadStandingOrder5Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-13T15:59:01.633+01:00")
public class OBReadStandingOrder5Data {
    @JsonProperty("StandingOrder")
    private List<OBStandingOrder5> standingOrder = null;

    public OBReadStandingOrder5Data standingOrder(List<OBStandingOrder5> standingOrder) {
        this.standingOrder = standingOrder;
        return this;
    }

    public OBReadStandingOrder5Data addStandingOrderItem(OBStandingOrder5 standingOrderItem) {
        if (this.standingOrder == null) {
            this.standingOrder = new ArrayList<OBStandingOrder5>();
        }
        this.standingOrder.add(standingOrderItem);
        return this;
    }

    /**
     * Get standingOrder
     *
     * @return standingOrder
     **/
    @Valid
    @ApiModelProperty(value = "")
    public List<OBStandingOrder5> getStandingOrder() {
        return standingOrder;
    }

    public void setStandingOrder(List<OBStandingOrder5> standingOrder) {
        this.standingOrder = standingOrder;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OBReadStandingOrder5Data obReadStandingOrder5Data = (OBReadStandingOrder5Data) o;
        return Objects.equals(this.standingOrder, obReadStandingOrder5Data.standingOrder);
    }

    @Override
    public int hashCode() {
        return Objects.hash(standingOrder);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class OBReadStandingOrder5Data {\n");

        sb.append("    standingOrder: ").append(toIndentedString(standingOrder)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

