/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * OpenAPI spec version: v3.1.2-RC1
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.org.openbanking.datamodel.account;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * OBReadDirectDebit1Data
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-06-13T15:59:01.633+01:00")
public class OBReadDirectDebit1Data {
  @JsonProperty("DirectDebit")
  private List<OBReadDirectDebit1DataDirectDebit> directDebit = null;

    public OBReadDirectDebit1Data directDebit(List<OBReadDirectDebit1DataDirectDebit> directDebit) {
    this.directDebit = directDebit;
    return this;
  }

    public OBReadDirectDebit1Data addDirectDebitItem(OBReadDirectDebit1DataDirectDebit directDebitItem) {
    if (this.directDebit == null) {
        this.directDebit = new ArrayList<OBReadDirectDebit1DataDirectDebit>();
    }
    this.directDebit.add(directDebitItem);
    return this;
  }

  /**
   * Get directDebit
   * @return directDebit
  **/
  @Valid
  @ApiModelProperty(value = "")
  public List<OBReadDirectDebit1DataDirectDebit> getDirectDebit() {
    return directDebit;
  }

    public void setDirectDebit(List<OBReadDirectDebit1DataDirectDebit> directDebit) {
    this.directDebit = directDebit;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OBReadDirectDebit1Data obReadDirectDebit1Data = (OBReadDirectDebit1Data) o;
    return Objects.equals(this.directDebit, obReadDirectDebit1Data.directDebit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(directDebit);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OBReadDirectDebit1Data {\n");
    
    sb.append("    directDebit: ").append(toIndentedString(directDebit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

